import type { Upgrade } from "./upgrade.svelte";
import { BasicUpgrade } from "./basic-upgrade.svelte";
import { Stats } from "$lib/stats/stat-manager";

export const allUpgrades: Upgrade[] =
    [
        new BasicUpgrade("double-click", "Double Click", 10,
            new Map([[Stats.ScorePerClick, 1]]), undefined),
        new BasicUpgrade("fast-internet", "Fast Internet", 25,
            undefined, new Map([[Stats.ScorePerSecond, 0.05]])),
        new BasicUpgrade("grip-trainer", "Grip Trainer", 50,
            new Map([[Stats.ScorePerClick, 2]]), undefined),
        new BasicUpgrade("multithreaded-denial", "Multithreaded Denial", 500,
            undefined, new Map([[Stats.ScorePerSecond, 0.1]])),
        new BasicUpgrade("keyboard-shortcuts", "Keyboard Shortcuts", 100,
            new Map([[Stats.ScorePerClick, 5]]), undefined),
        new BasicUpgrade("offshore-efficiency", "Offshore Efficiency", 1000,
            undefined, new Map([[Stats.ScorePerSecond, 0.5]])),
        new BasicUpgrade("laser-printer", "Laser Printer", 250,
            new Map([[Stats.ScorePerClick, 10]]), undefined),
        new BasicUpgrade("policy-parser", "Policy Parser", 2000,
            undefined, new Map([[Stats.ScorePerSecond, 1]])),
        new BasicUpgrade("batch-processing", "Batch Processing", 5000,
            undefined, new Map([[Stats.ScorePerSecond, 2]])),
        new BasicUpgrade("extra-stapler", "Extra Stapler", 1000,
            new Map([[Stats.ScorePerClick, 15]]), undefined),
        new BasicUpgrade("legal-team", "Legal Team", 15000,
            undefined, new Map([[Stats.ScorePerSecond, 5]])),
        new BasicUpgrade("ergonomic-mouse", "Ergonomic Mouse", 3000,
            new Map([[Stats.ScorePerClick, 20]]), undefined),
        new BasicUpgrade("server-upgrade", "Server Upgrade", 25000,
            undefined, new Map([[Stats.ScorePerSecond, 10]])),
        new BasicUpgrade("auto-denial-software", "Auto Denial Software", 10000,
            undefined, new Map([[Stats.ScorePerSecond, 15]])),
        new BasicUpgrade("pre-filled-templates", "Pre-filled Templates", 5000,
            new Map([[Stats.ScorePerClick, 30]]), undefined),
        new BasicUpgrade("streamlined-paperwork", "Streamlined Paperwork", 50000,
            undefined, new Map([[Stats.ScorePerSecond, 20]])),
        new BasicUpgrade("dedicated-line", "Dedicated Line", 20000,
            undefined, new Map([[Stats.ScorePerSecond, 25]])),
        new BasicUpgrade("policy-optimizer", "Policy Optimizer", 75000,
            undefined, new Map([[Stats.ScorePerSecond, 50]])),
        new BasicUpgrade("ai-enhancer", "AI Enhancer", 100000,
            undefined, new Map([[Stats.ScorePerSecond, 75]])),
        new BasicUpgrade("click-multiplier", "Click Multiplier", 20000,
            new Map([[Stats.ScorePerClick, 50]]), undefined),
        new BasicUpgrade("denial-bot", "Denial Bot", 250000,
            undefined, new Map([[Stats.ScorePerSecond, 100]])),
        new BasicUpgrade("cloud-computing", "Cloud Computing", 500000,
            undefined, new Map([[Stats.ScorePerSecond, 150]])),
        new BasicUpgrade("holographic-interface", "Holographic Interface", 1000000,
            undefined, new Map([[Stats.ScorePerSecond, 200]])),
        new BasicUpgrade("quantum-denial", "Quantum Denial", 2000000,
            undefined, new Map([[Stats.ScorePerSecond, 300]])),
        new BasicUpgrade("virtual-assistant", "Virtual Assistant", 500000,
            new Map([[Stats.ScorePerClick, 100]]), undefined),
        new BasicUpgrade("denial-synergy", "Denial Synergy", 5000000,
            undefined, new Map([[Stats.ScorePerSecond, 400]])),
        new BasicUpgrade("bureaucracy-mastery", "Bureaucracy Mastery", 10000000,
            undefined, new Map([[Stats.ScorePerSecond, 500]])),
        new BasicUpgrade("laser-guided-mouse", "Laser-Guided Mouse", 5000000,
            new Map([[Stats.ScorePerClick, 200]]), undefined),
        new BasicUpgrade("ultra-automation", "Ultra Automation", 20000000,
            undefined, new Map([[Stats.ScorePerSecond, 1000]]))
    ];